/* 世界觀擴充：新怪物（30 種，含手繪像素圖）、新遺物（28 件）、所有遺物的故事與所有怪物／首領的圖鑑介紹。
 * 世界觀設定（不在遊戲中明說）見 docs/世界觀.md；新增文字請保持「只暗示、不解釋」。
 * 載入順序：monsters.js 之後、store.js 之前（store 的預設已解鎖遺物要看得到新遺物）。 */
(() => {
  /* ---------- 像素圖：每列只寫左半（6 字元），自動鏡射成 12×12（與 monsters.js 相同） ---------- */
  const sym = rows => rows.map(r => r.length === 12 ? r : r + [...r].reverse().join(''));
  const ART = {
    paperbird: ['......', '....kk', '...kww', 'k..krw', 'Wk.kww', 'wWkWww', '.wWWww', '..wWWw', '...kWW', '....kW', '.....k', '......'],
    stamp: ['....kk', '...knn', '...knn', '..kkkk', '.knnnn', 'knnnnn', 'knwknn', 'knnnnn', 'kkkkkk', 'kRRRRR', 'krRrRr', '.kkkkk'],
    dustbunny: ['..k...', '.kWk..', '.kWk..', '..kWkk', '.kWWWW', 'kWWkWW', 'kWWWWp', 'kWsWWW', 'kWWWWW', '.ksWWs', '..kkkk', '......'],
    tack: ['.....k', '....ks', '....ks', '..kkky', '.kyyyy', '..kkkk', '.kbbbb', 'kbBbbB', 'kbbbbb', '.kbwkb', 'k.kkkk', '......'],
    moss: ['......', '..g.gg', '.gGgGg', 'gGggGg', 'gggGgg', 'gGwkgG', 'ggggGg', 'gGgggg', '.gGggp', '..gGgg', '...ggg', '......'],
    inkdrop: ['.....k', '....kV', '....kV', '...kVV', '..kVvV', '.kVvVV', '.kVwkV', 'kVVVVV', 'kVVVkk', 'kVVVVV', '.kVVVV', '..kkkk'],
    lampmoth: ['...k..', '....k.', 'kkk.kn', 'kyyknn', 'kyhykn', 'kyyykn', '.kyokn', 'kyyykn', 'kooykn', '.kook.', '..kk..', '......'],
    chair: ['.kkkkk', '.knnnn', '.knwkn', '.knnnn', '.knNNN', '.knnnn', '.kkkkk', 'knnnnn', 'kkkkkk', '.kn...', '.kn...', '.kk...'],
    abacus: ['kkkkkk', 'kNNNNN', 'kNrnrn', 'kNnrnr', 'kNNNNN', 'kNwkrn', 'kNnrnr', 'kNrnrn', 'kNNNNN', 'kkkkkk', '.k....', '......'],
    beetle: ['.k....', '..k.kk', '...kss', '..kswk', '.kkkkk', 'kVvVVk', 'kVVVVk', 'kVvVVk', 'kVVVVk', '.kVVVk', 'k.kkkk', '......'],
    lanternghost: ['....kk', '...kkk', '..kRRR', '.kRrrr', 'kRryrr', 'kRwkrr', 'kRrrrr', 'kRrrkk', '.kRrrr', '..kRRR', '...kkk', '....ky'],
    tidepool: ['......', '......', '......', '......', '....kk', '..kkVV', '.kVwkV', 'kVVVVV', 'kVvVVV', 'kVVVVV', '.kVVVV', '..kkkk'],
    bellwraith: ['....kk', '...kss', '..kssS', '..ksSS', '.ksssS', '.kswkS', '.ksssS', 'kssssS', 'kkkkkk', '....ky', '...ccc', '....c.'],
    nib: ['.....k', '....ks', '...ksk', '...ksk', '..kssk', '..kwkk', '.kssSk', '.kssSk', 'kssSSk', 'kyyyyy', 'kkkkkk', '.kVVVV'],
    mask: ['..kkkk', '.kVVVV', 'kVVkkk', 'kVkwww', 'kVkwkk', 'kVkwww', 'kVkwwr', 'kVkwww', 'kVVkww', '.kVVkk', '.kVVVV', '..kkkk'],
    shadowcat: ['.k....', 'kSk...', 'kSSk..', 'kSSSkk', 'kSSSSS', 'kSykSS', 'kSSSSS', 'kSSSSp', '.kSSSS', '..kSSS', '...kkk', '......'],
    sandglass: ['kkkkkk', '.knnnn', '.kcccc', '..kyyy', '..kwky', '...kyy', '....ky', '...kcy', '..kcyy', '.kyyyy', '.knnnn', 'kkkkkk'],
    mirror: ['...kkk', '..kyyy', '.kyccc', '.kycwc', 'kycccc', 'kycwkc', 'kycccc', 'kycccS', '.kyccc', '.kyyyy', '..kkyk', '..kyyy'],
    inkwhale: ['....c.', '.....c', '..kkkk', '.kVVVV', 'kVVVVV', 'kVwkVV', 'kVVVVV', 'kVkkkk', 'kVvvvv', '.kvvvv', 'k.kkkk', 'k.....'],
    lampeater: ['..kkkk', '.kSSSS', 'kSSSSS', 'kSykSS', 'kSSSSS', 'kkkkkk', 'krwrwr', 'krrryy', 'krrrrh', 'kwrwrw', 'kkkkkk', '.kSk..'],
    grader: ['.....s', '.....s', '..kkkk', '.kllll', '.klwkl', '.kllll', '..kllr', '...kkk', 'knnnnn', 'k.knnn', 'r.knkn', '..kk.k'],
    twins: ['.kkk..', 'kNNNk.', 'kllNk.', 'kwklk.', 'kllpk.', '.kllk.', '..kk..', '.kbbk.', 'kbbbbk', 'kbbbbk', 'kbkbbk', '.k..kk'],
    blankone: ['..kkkk', '.kSSSS', 'kSSkkk', 'kSkWWW', 'kSkWWW', 'kSkWWW', 'kSSkWW', '.kSSkk', 'kSSSSS', 'kSsSSS', 'kSsSSS', 'kkkkkk'],
    tide: ['.....c', '...ccc', '..cVVV', '.cVVVV', 'cVVwkV', 'cVVVVV', '.VVVVV', 'VVvVVV', 'VvVVvV', 'VVVVVV', 'cVcVcV', 'cccccc'],
    bellkeeper: ['..kkkk', '.kWWWW', 'kWWkkk', 'kWkkyk', 'kWkkkk', '.kWWkk', 'kWWWWW', 'kWWkyy', 'kWWkyy', 'kWWkkk', 'kWWWWW', 'kkkkkk']
  };
  Object.entries(ART).forEach(([k, half]) => {
    const rows = sym(half);
    SP.MAPS[k] = [rows, ['............'].concat(rows.slice(0, 5), rows.slice(6))];
  });

  /* ---------- 新怪物（30 種） ---------- */
  C.MONSTERS.push(
    // 淺層
    { id: 'paperbird', name: '紙鶴', tile: 'paperbird', filter: 'none', hp: 0.8, atk: 0.9, tier: 0, traits: ['dodge'], fx: 'needle', desc: '紙片翅膀輕飄飄的，攻擊常常落空。' },
    { id: 'stamp', name: '印章怪', tile: 'stamp', filter: 'none', hp: 1.0, atk: 0.85, tier: 0, traits: ['guard'], fx: 'slam', desc: '每隔幾題就蓋下一個「駁回」，擋掉你的攻擊。' },
    { id: 'dustbunny', name: '塵兔', tile: 'dustbunny', filter: 'none', hp: 0.85, atk: 0.85, tier: 0, traits: ['thief'], desc: '從書架底下竄出來，順手摸走你的金幣。' },
    { id: 'tack', name: '圖釘蟲', tile: 'tack', filter: 'none', hp: 0.9, atk: 0.85, tier: 0, traits: ['thorny'], fx: 'needle', desc: '背上插著一根圖釘，打牠會被刺到。' },
    { id: 'moss', name: '苔球', tile: 'moss', filter: 'none', hp: 1.1, atk: 0.75, tier: 0, traits: ['heal', 'thick'], desc: '軟綿綿、很耐打，還會慢慢長回來。' },
    { id: 'inkdrop', name: '墨滴', tile: 'inkdrop', filter: 'none', hp: 0.85, atk: 0.85, tier: 0, traits: ['split'], fx: 'ink', desc: '打到一半會分裂再生。' },
    // 中層
    { id: 'lampmoth', name: '燈蛾', tile: 'lampmoth', filter: 'none', hp: 0.85, atk: 1.1, tier: 1, traits: ['scorch', 'dodge'], fx: 'fire', desc: '翅膀上的鱗粉一碰就著火。' },
    { id: 'chair', name: '考場椅精', tile: 'chair', filter: 'none', hp: 1.2, atk: 0.9, tier: 1, traits: ['harden', 'thick'], fx: 'slam', desc: '結實的木頭，越打越硬。' },
    { id: 'abacus', name: '算盤精', tile: 'abacus', filter: 'none', hp: 1.0, atk: 1.0, tier: 1, traits: ['guard', 'ambush'], fx: 'slam', desc: '算準了出手時機：先發制人，還會格擋。' },
    { id: 'beetle', name: '墨甲蟲', tile: 'beetle', filter: 'none', hp: 1.1, atk: 1.0, tier: 1, traits: ['armor', 'rot'], desc: '硬殼擋傷害，身上的墨會腐蝕你的護甲。' },
    { id: 'lanternghost', name: '迷途燈籠', tile: 'lanternghost', filter: 'none', hp: 0.9, atk: 1.1, tier: 1, traits: ['scorch', 'spite'], fx: 'fire', desc: '燙手的燈籠，熄滅前還會燒你一下。' },
    { id: 'tidepool', name: '墨潮水窪', tile: 'tidepool', filter: 'none', hp: 1.0, atk: 0.95, tier: 1, traits: ['split', 'chill'], fx: 'ink', desc: '冰冷的墨水，打散了又聚回來。' },
    // 深層
    { id: 'proctor', name: '監考騎士', tile: 96, filter: 'hue-rotate(180deg) saturate(1.3) brightness(.85)', hp: 1.3, atk: 1.1, tier: 2, traits: ['guard', 'charge'], fx: 'slam', desc: '舉盾、蓄力，一板一眼的重擊。' },
    { id: 'bellwraith', name: '鐘聲幽靈', tile: 'bellwraith', filter: 'none', hp: 1.0, atk: 1.15, tier: 2, traits: ['silence', 'shock'], fx: 'orb', desc: '鐘聲震得你手發麻，技能也用不出來。' },
    { id: 'nib', name: '筆尖刺客', tile: 'nib', filter: 'none', hp: 0.9, atk: 1.35, tier: 2, traits: ['ambush', 'thorny'], fx: 'needle', desc: '第一擊又快又準，碰到還會被刺傷。' },
    { id: 'mask', name: '假面考官', tile: 'mask', filter: 'none', hp: 1.0, atk: 1.2, tier: 2, traits: ['dodge', 'weaken'], fx: 'orb', desc: '看不透的表情，被盯著答錯會越來越沒力。' },
    { id: 'shadowcat', name: '影貓', tile: 'shadowcat', filter: 'none', hp: 0.9, atk: 1.25, tier: 2, traits: ['dodge', 'thief', 'swift'], desc: '來無影去無蹤，還會叼走你的金幣。' },
    { id: 'sandglass', name: '沙漏魔', tile: 'sandglass', filter: 'none', hp: 1.15, atk: 1.05, tier: 2, traits: ['bloat', 'guard'], mechs: ['haste'], desc: '選擇題要在時限內作答，拖越久牠越強。' },
    { id: 'mirror', name: '鏡中考生', tile: 'mirror', filter: 'none', hp: 1.1, atk: 1.15, tier: 2, traits: ['mirror', 'siphon'], fx: 'orb', desc: '反彈你的暴擊，還會偷走你的力量。' },
    // 深淵
    { id: 'archivist', name: '失憶的館員', tile: 84, filter: 'grayscale(.6) sepia(.6) brightness(.85)', hp: 1.15, atk: 1.2, tier: 3, traits: ['silence', 'heal', 'weaken'], fx: 'orb', desc: '封印技能、削弱力氣，還會自我修復。' },
    { id: 'inkwhale', name: '墨鯨', tile: 'inkwhale', filter: 'none', hp: 1.7, atk: 1.05, tier: 3, traits: ['thick', 'chill', 'split'], fx: 'ink', desc: '巨大的身軀，打到一半還會再生。' },
    { id: 'chainknight', name: '鎖鏈騎士', tile: 97, filter: 'grayscale(1) brightness(.6) contrast(1.2)', hp: 1.35, atk: 1.25, tier: 3, traits: ['armor', 'undying'], fx: 'slam', desc: '厚重鎧甲，倒下一次還會再站起來。' },
    { id: 'lampeater', name: '噬燈者', tile: 'lampeater', filter: 'none', hp: 1.2, atk: 1.3, tier: 3, traits: ['drain', 'hex', 'frenzy'], fx: 'fire', desc: '吸血、厄運，血越少越兇猛。' },
    { id: 'grader', name: '閱卷傀儡', tile: 'grader', filter: 'none', hp: 1.3, atk: 1.25, tier: 3, traits: ['charge', 'expose', 'harden'], fx: 'slam', desc: '蓄力批改，越打越硬，答錯就露出破綻。' },
    { id: 'twins', name: '雙生考生', tile: 'twins', filter: 'none', hp: 1.1, atk: 1.3, tier: 3, traits: ['swarm', 'spite'], desc: '兩個人一起出手，倒下時還會留下怨念。' },
    // 深淵最深處
    { id: 'blankone', name: '無字者', tile: 'blankone', filter: 'none', hp: 1.4, atk: 1.45, tier: 4, traits: ['dodge', 'hex', 'silence'], fx: 'orb', desc: '難以命中、讓你失準，還封印技能。' },
    { id: 'tide', name: '墨潮巨浪', tile: 'tide', filter: 'none', hp: 1.6, atk: 1.4, tier: 4, traits: ['swarm', 'chill', 'scorch'], fx: 'ink', desc: '一波接一波，又冷又燙。' },
    { id: 'bellkeeper', name: '白塔守鐘人', tile: 'bellkeeper', filter: 'none', hp: 1.7, atk: 1.3, tier: 4, traits: ['charge', 'armor', 'undying'], fx: 'slam', desc: '厚重、不倒，蓄力的鐘擊非常致命。' },
    { id: 'eraserking', name: '抹消之王', tile: 'eraser', filter: 'hue-rotate(250deg) saturate(1.8) brightness(.75)', hp: 1.5, atk: 1.4, tier: 4, traits: ['siphon', 'rot', 'mirror'], desc: '一點一點擦掉你的力量與護甲。' },
    { id: 'lastexaminee', name: '最後的考生', tile: 88, filter: 'grayscale(.8) brightness(.7) drop-shadow(0 0 4px #b8a0ff)', hp: 1.45, atk: 1.5, tier: 4, traits: ['undying', 'frenzy', 'spite'], desc: '不肯倒下，越接近終點越瘋狂。' }
  );

  /* ---------- 新遺物（28 件）：since 2 → 舊存檔自動補解鎖（store.js） ---------- */
  C.RELICS.push(
    { id: 'match', name: '燈守的火柴', icon: '🔥', rar: 1, since: 2, desc: '每場戰鬥第一次答對，傷害 ×1.5' },
    { id: 'pass', name: '白塔通行證', icon: '🎫', rar: 1, since: 2, desc: '最大生命 +10，防禦力 +1', gain: p => { p.maxHp += 10; p.hp += 10; p.def += 1; } },
    { id: 'chalk', name: '半截粉筆', icon: '✏️', rar: 1, since: 2, desc: '攻擊力 +2，暴擊率 +4%', gain: p => { p.atk += 2; p.crit += 0.04; } },
    { id: 'cork', name: '墨水瓶塞', icon: '🍶', rar: 1, since: 2, desc: '中毒與著火造成的傷害減半' },
    { id: 'bookmark', name: '摺角書籤', icon: '🔖', rar: 1, since: 2, desc: '每場戰鬥開始獲得 5 護盾', gain: p => { p.startShield = (p.startShield || 0) + 5; } },
    { id: 'wick', name: '燭芯', icon: '🕯️', rar: 1, since: 2, desc: '擊敗怪物時回復 6 生命' },
    { id: 'letter', name: '未寄出的信', icon: '✉️', rar: 1, since: 2, desc: '每擊敗 3 隻怪物，獲得 1 瓶小回復藥' },
    { id: 'blanket', name: '守夜人的毯子', icon: '🧣', rar: 1, since: 2, desc: '最大生命 +5；篝火休息回復量 +30%', gain: p => { p.maxHp += 5; p.hp += 5; } },
    { id: 'omamori', name: '考生的護身符', icon: '🧧', rar: 2, since: 2, desc: '生命低於 30% 時，受到的傷害 -30%' },
    { id: 'admit', name: '舊准考證', icon: '📇', rar: 2, since: 2, desc: '經驗值 +15%，金幣 +15%', gain: p => { p.xpMul += 0.15; p.goldMul += 0.15; } },
    { id: 'bell', name: '監考鈴', icon: '🔔', rar: 2, since: 2, desc: '怪物蓄力時答對，傷害 ×1.8' },
    { id: 'lens', name: '閱卷放大鏡', icon: '🔍', rar: 2, since: 2, desc: '對精英與首領的傷害 +20%' },
    { id: 'oldnotes', name: '褪色的錯題本', icon: '📓', rar: 2, since: 2, desc: '答錯時，先獲得 4 點護盾再承受反擊' },
    { id: 'sliderule', name: '銅製計算尺', icon: '📏', rar: 2, since: 2, desc: '多選題與填答題答對時，連擊額外 +1' },
    { id: 'pendulum', name: '白塔鐘擺', icon: '🕰️', rar: 2, since: 2, desc: '每場戰鬥中，每第 4 次答對必定暴擊' },
    { id: 'shell', name: '墨潮貝殼', icon: '🐚', rar: 2, since: 2, desc: '每次受到反擊有 20% 機率完全擋下' },
    { id: 'rustkey', name: '鏽蝕的鑰匙', icon: '🗝️', rar: 2, since: 2, desc: '打開寶箱時多一件遺物可以選（4 選 1）' },
    { id: 'inkfeather', name: '墨染羽毛', icon: '✒️', rar: 2, since: 2, desc: '答對時 15% 機率追加一次 80% 的攻擊' },
    { id: 'brokenglass', name: '碎裂的眼鏡', icon: '🕶️', rar: 2, since: 2, desc: '暴擊率 +3%，暴擊傷害 +30%', gain: p => { p.crit += 0.03; p.critDmg += 0.3; } },
    { id: 'medal7', name: '第七屆紀念章', icon: '🏅', rar: 3, since: 2, desc: '每 1 層連擊，暴擊率額外 +5%', locked: true, cost: 110 },
    { id: 'blankpage', name: '空白之頁', icon: '📄', rar: 3, since: 2, desc: '擊敗怪物時，所有技能冷卻 -1', locked: true, cost: 120 },
    { id: 'lampheart', name: '燈守的燈芯', icon: '🏮', rar: 3, since: 2, desc: '最大生命 +25；每進入新樓層回復 3 生命', locked: true, cost: 140, gain: p => { p.maxHp += 25; p.hp += 25; } },
    { id: 'answersheet', name: '失落的答案卷', icon: '📜', rar: 3, since: 2, desc: '單選題有 35% 機率開場刪去 1 個錯誤選項', locked: true, cost: 150 },
    /* 首領遺物 */
    { id: 'redpen', name: '命題者的紅筆', icon: '🖊️', rar: 4, boss: true, since: 2, desc: '攻擊力 +4；每次答對使怪物攻擊力 -1（最多降到一半）', gain: p => { p.atk += 4; } },
    { id: 'towerbell', name: '白塔之鐘', icon: '🛎️', rar: 4, boss: true, since: 2, desc: '暴擊率 +5%；每場戰鬥開始獲得 15% 最大生命的護盾', gain: p => { p.crit += 0.05; } },
    { id: 'lastlamp', name: '最後一盞燈', icon: '💡', rar: 4, boss: true, since: 2, desc: '生命低於 50% 時攻擊 +35%；答對時額外回復 3 生命' },
    { id: 'inkheart', name: '墨潮之心', icon: '🖤', rar: 4, boss: true, since: 2, desc: '攻擊 +30%，但每答一題失去 1 生命（不會因此倒下）', gain: p => { p.atkMul += 0.3; } }
  );

  /* ---------- 遺物的故事 ---------- */
  const RELIC_LORE = {
    sword: '監考騎士團的制式佩劍。劍柄刻著「公正」兩個字，被許多隻手磨得發亮。',
    buckler: '白塔後院那棵老橡樹做的。樹在那一晚倒下了，盾卻還記得陽光的溫度。',
    belt: '一個能把整座書庫背下來的人留下的。他說，最難的不是記住，是不肯忘記。',
    fang: '鐘樓蝙蝠的牙。牠們靠考生的焦慮過活，所以從來沒有餓過。',
    clover: '夾在一本歷屆試題裡，壓得很平。旁邊用鉛筆寫著：「這次一定可以。」',
    purse: '行商說是從一個沒走出白塔的人身上撿來的。袋子還在習慣性地數錢。',
    bracer: '某位應考者用來壓住顫抖手腕的護腕。答得越順，它扣得越緊。',
    owlglass: '鏡片上有一層淡淡的墨痕。戴上之後，錯的選項看起來就是不太對勁。',
    thorns: '監考騎士團懲戒用的鎧甲，本來是給作弊的人穿的。現在它保護你。',
    hourglass: '考場每張桌上都有一個。那一晚之後，大部分的沙都停了，只有這一個還在流。',
    quill: '燈守寫下答案用的筆。筆尖從不沾墨，卻總寫得出字。',
    ember: '從營火裡挑出來的一小塊。有人說，那堆火是塔外最後一盞沒有熄的燈。',
    badge: '行商工會的舊徽章。工會早就散了，只剩那個戴兜帽的人還在做生意。',
    orb: '一顆不太純的魂晶，裡面還留著某人讀書讀到天亮的記憶。',
    phoenix: '焰羽鳳凰每重生一次就會掉下一根。牠是唯一不怕墨的鳥。',
    berserk: '戴上之後，耳邊只剩下心跳聲。上一個主人在半路脫下了它，就再也沒有戴回去。',
    calm: '白塔門口的台階石。每個考生進場前，都在這裡深呼吸過。',
    soul: '瓶子是空的，搖起來卻有聲音。行商說最好別打開。',
    crown: '第一屆榜首的冠冕。上面本來有七顆寶石，現在只剩一顆。',
    lantern: '燈守的入門提燈。燈罩內側刻著一行小字：「照亮一頁，就少遺忘一頁。」',
    anvil: '流浪鐵匠的老家當。他說白塔的鎧甲都是在這上面打的，只是沒人記得了。',
    mimicTooth: '寶箱怪原本只是考場的置物箱，裝著考生的家當。牠們還在等主人回來領。',
    philo: '第一盞燈的燈芯。燈早就熄了，石頭卻還是溫的。',
    dragonheart: '一頭讀完整座書庫的龍留下的心臟。牠在找一個不存在於書裡的答案。',
    tome: '禁書區館長的書。每翻開一次，就多出一頁剛寫好的題目。',
    cloak: '白塔還有舞會的年代穿的披風。內襯繡著邀請函上的日期——正好是那一晚。',
    mjolnir: '白塔頂端的避雷針熔成的鎚子。它曾經替整座塔擋下每一道落雷。',
    compass: '指針不指北，而是指向最近的出口。在塔裡，它常常轉個不停。',
    phoenixheart: '鳳凰第一次重生時留下的心。牠把它留給還想再試一次的人。',
    chaosdice: '骰子賭徒的寶貝。他說這顆骰子從沒擲出過同樣的點數兩次——他也從沒說過謊。',
    aegis: '監考騎士團團長的盾。盾面映出的不是你的臉，而是你最想答對的那一題。',
    hourcrown: '從鐘塔守衛頭上取下的齒輪冠。戴著它答題時，時間會走得慢一點。',
    yuzucharm: '那棵柚子樹是一個想回家的考生種下的。果子很酸，但吃過的人都想起了家。',
    koiscale: '池裡的錦鯉吞下了許多祈願的硬幣。牠記得每一個願望，也記得哪些實現了。',
    teacup: '貓不需要記住任何事，所以墨碰不到牠們。茶會每年都照常舉行。',
    nightowl: '杯底有一圈褐色的痕跡。塔裡的燈還亮著的年代，每張書桌上都有一只這樣的杯子。',
    match: '點燈用的火柴，只剩下最後一根。燈守說過：第一下最重要。',
    pass: '蓋著「第七屆」印章的通行證。有效期限那一欄被墨染黑了。',
    chalk: '黑板前那位老師用剩的粉筆。他講到一半，外面就開始下起黑色的雨。',
    cork: '墨水瓶的軟木塞。如果那天晚上，有人記得把瓶子蓋好……',
    bookmark: '停在某一頁的書籤。那一頁之後的內容，再也沒有人讀過。',
    wick: '燃盡的蠟燭留下的芯。燭火妖們一直想把它要回去。',
    letter: '地址寫好了，郵票也貼了。信的第一句是：「考完我就回家。」',
    blanket: '在營火旁守夜的人留下的毯子。他把位置讓給了你，自己往塔的方向走去。',
    omamori: '家人親手縫的護身符，布已經褪色。裡面的紙條寫著：「平安回來就好。」',
    admit: '照片被墨暈開，看不清是誰。座號欄寫著 0。',
    bell: '宣告開始與結束的鈴。它在那一晚響了一整夜。',
    lens: '閱卷官找錯字用的放大鏡。拿它對著怪物，能隱約看出牠們原本是什麼。',
    oldnotes: '每一題都訂正過三次。主人沒有留下名字，只留下這一本。',
    sliderule: '刻度細到肉眼幾乎看不清。背面記著一道沒有算完的式子。',
    pendulum: '白塔大鐘的鐘擺，掉進了深處。它仍照著原本的節奏擺動，像在等誰回來。',
    shell: '從墨裡撈起來的貝殼。貼在耳邊，能聽見翻書的聲音。',
    rustkey: '開考場置物櫃用的鑰匙。寶箱怪們看到它，會突然安靜下來。',
    inkfeather: '紙鶴身上掉下來的羽毛。被墨浸過的東西，都會記得怎麼傷人。',
    brokenglass: '一邊的鏡片碎了。透過碎的那一邊看，弱點反而更清楚。',
    medal7: '原本要在放榜那天發給每位考生的紀念章。一枚都沒有發出去。',
    blankpage: '一張什麼都沒寫的紙。不知道為什麼，拿著它的時候，腦袋特別清醒。',
    lampheart: '一位燈守把自己的燈芯交給了下一個人，然後走進了墨裡。',
    answersheet: '寫滿答案的考卷，題目卻不見了。其中有些答案，你好像在哪裡看過。',
    redpen: '出題的人批改用的紅筆。被它劃過的東西，會開始懷疑自己是不是對的。',
    towerbell: '白塔頂上的大鐘。鐘聲響起時，那些騎士會短暫地想起自己是誰。',
    lastlamp: '燈守們合力守住的最後一盞燈。你越暗的時候，它越亮。',
    inkheart: '墨的源頭凝結成的心臟。握著它會變強，也會一點一點被吞沒。'
  };

  /* ---------- 怪物的圖鑑介紹 ---------- */
  const MON_LORE = {
    slime: '打翻的漿糊吸了墨水之後活了過來。牠們不壞，只是黏上什麼就不肯放。',
    rat: '書庫的老鼠啃了太多藏書，學會了算數——尤其是算你的金幣。',
    bat: '住在白塔的鐘樓裡。那一晚之後，牠們改吸考生的焦慮，越緊張的越香。',
    shroom: '長在潮濕書頁上的菇。孢子裡是被遺忘的段落，吸進去會頭痛。',
    book: '一本吞了太多題目的參考書。牠不想讓你答對，因為答案是牠的。',
    snail: '從燭台底下爬出來的蝸牛，殼上還沾著蠟。牠背著一小團火，走得很慢。',
    spider: '在書架之間結網，專抓迷路的字。網上的字，讀起來都是錯的。',
    ghost: '某位沒有交卷的考生。他還在找自己的座位。',
    skeleton: '白塔的舊衛兵。骨頭忘記了怎麼倒下，所以一直站著。',
    eye: '監考時用來看守考場的眼睛。主人不在了，它仍然盯著每一個人。',
    bandit: '趁亂溜進塔裡的人。他們偷東西，也偷別人的答案。',
    crab: '從黑色的海裡爬上岸的甲殼生物。牠的殼是被染紅的。',
    mage: '曾在塔裡研究咒語的學者。他把一個字念了太多次，忘了它是什麼意思。',
    wisp: '熄滅的燈留下的最後一點火。它不甘心，所以到處亂竄。',
    guard: '騎士團的盔甲，裡面早就空了。它還照著巡邏路線走。',
    cyclops: '負責搬書架的巨人。另一隻眼睛，被那一晚的浪帶走了。',
    golem: '白塔的地基石。聽了太多年的課，自己站了起來。',
    fallen: '寧願留在墨裡也不肯認輸的騎士。他還在等一個對手。',
    warlock: '讀過禁書的人。他知道最後一題寫了什麼，所以不再開口。',
    wraith: '沒有考完的人留下的遺憾。它不是恨你，只是恨自己。',
    inkblot: '打翻的墨水沒有擦乾淨，就慢慢長出了眼睛。',
    bee: '在考卷堆裡築巢的蜂。每一根針，都是一個紅色的叉。',
    goblin: '替行商跑腿的小傢伙。找不到老闆之後，乾脆把貨款留給自己。',
    candle: '陪考生熬過無數個夜晚的蠟燭。它不想再被吹熄了。',
    worm: '真正的書蟲。牠吃下的每一頁，世界就少了一頁。',
    jelly: '在黑色的海裡漂流的水母，觸手上纏著別人的夢。',
    frog: '許願池旁的青蛙。牠聽過太多次「這次一定會過」，聽到變成了詛咒。',
    pumpkin: '白塔廚房的南瓜，本來要做成放榜那天的派。',
    icebat: '鐘樓最高處的蝙蝠。那裡冷得連墨都結成了冰。',
    sandcrab: '深處有一片由碎掉的沙漏堆成的沙丘，這些蟹就住在那裡。',
    moth: '被燈火吸引的蛾。燈熄了以後，牠們開始啃彼此的翅膀。',
    crystal: '魂晶聚得太多，長出了自己的意志。它很討厭被人拿走。',
    imp: '從暖爐裡跑出來的小東西，最喜歡燒掉沒寫完的草稿。',
    bombling: '考場裡積了太久的壓力。總有一天會爆開。',
    shade: '躲在書頁陰影裡的人。他們說，自己是替「委員會」做事的。',
    witch: '她曾經是燈守之一。她想用別人的力量，讓自己的燈重新亮起來。',
    clock: '考場牆上的鐘。它只會做一件事：提醒你時間不夠了。',
    vampire: '白塔舞會的常客。那一晚，他是第一個發現水位在漲的人。他選擇留下來跳完最後一支舞。',
    viking: '從遠方來的應考者，想證明拿斧頭的人也能讀書。他到現在都還在證明。',
    plague: '想用藥治好「遺忘」的人。他的藥讓人忘得更快。',
    sporeking: '吃掉了整個書庫角落的菇。那個角落原本放著地理圖鑑。',
    hive: '考卷毒蜂的女王。她的巢是用一整屆的考卷糊成的。',
    voideye: '從最深處的空白裡睜開的眼睛。它看你的樣子，像在讀一張答錯的考卷。',
    bonelord: '很久以前的主考官。他到現在都不肯宣布考試結束。',
    abyssknight: '騎士團裡最後一個沒有撤退的人。他的盔甲裡裝滿了墨。',
    crystalgolem: '被魂晶慢慢覆蓋的魔像。裡面封著許多人的不甘心。',
    inkdragon: '在黑潮中誕生的龍。牠還很小，卻已經知道自己是誰的孩子。',
    goldslime: '吞下了行商金庫的史萊姆。牠很怕被抓到，所以跑得特別快。',
    eraser: '被用到只剩一小塊的橡皮擦。牠擦掉過太多正確答案，心裡一直過意不去。',
    pencil: '削得太尖的鉛筆。牠記得開考鈴響的那一刻，所以總是搶先出手。',
    fuzz: '考場地毯上的灰塵，在乾燥的冬天吸飽了靜電。',
    sprout: '從窗台盆栽冒出來的芽。牠還沒學會害怕。',
    cloud: '考前一晚壓在考生頭頂的那朵烏雲，終於有了形體。',
    scarecrow: '白塔農園的稻草人，身上穿著某個考生忘記帶走的外套。',
    tortoise: '圖書館前池塘裡的老龜。那一晚牠把頭縮了進去，就再也沒有伸出來。',
    snowman: '孩子們在塔前堆的雪人。冬天一直沒有過去，所以它也沒有融化。',
    piranha: '被丟進許願池的魚。牠們吃硬幣，也吃手指。',
    mummy: '用繃帶把自己綁在座位上的考生。他發過誓，沒考完不離開。',
    cactus: '擺在書桌上的小仙人掌，主人說它能吸收壞東西。它確實吸收了。',
    robot: '白塔的自動閱卷機。它還在給每一個人打零分。',
    wolf: '塔外森林裡的狼。牠們聞到燈火熄滅的味道，才敢靠近。',
    gargoyle: '屋簷上的雕像，負責替考場擋雨。現在的雨是黑色的。',
    minotaur: '地下迷宮的守衛。迷宮原本只是用來把考場隔開的。',
    siren: '在黑色的海上唱歌的女人。歌詞是上一屆的考古題。',
    reaper: '那位專門帶走放棄者的存在的學徒。他還在學怎麼分辨誰是真的放棄了。',
    phoenix: '每熄滅一盞燈，牠就重生一次。有人說，牠是在替燈哭泣。',
    treant: '白塔中庭的老樹。每一個考生都在它底下背過書。',
    kraken: '黑色的海最深處的東西。每一條觸手上都抓著一本沒有歸還的書。',
    cobra: '繞著禁書書架生長的蛇。被牠咬到的人，會永遠記錯一個字。',
    seraph: '曾經守護著「最後一題」的存在。那一題被寫下的瞬間，它就墜落了。',
    drake: '墨龍幼體長大後的樣子。牠已經不記得自己曾經是個孩子。',
    paperbird: '用寫錯的考卷摺成的紙鶴。摺的人說，摺滿一千隻就能及格。',
    stamp: '教務處的「駁回」印章。牠蓋過的申請，沒有一張通過。',
    dustbunny: '書架底下的灰塵團。打掃的人離開之後，牠們長出了耳朵。',
    tack: '把公告釘在佈告欄上的圖釘。最後一張公告寫著：「考試延期。」',
    moss: '長在石階上的青苔。牠在等有人再一次走過這段階梯。',
    inkdrop: '那片黑潮留下的一滴。把它打碎，它會變成兩滴。',
    lampmoth: '尋找光的蛾。牠們把你身上的火，當成了一盞燈。',
    chair: '坐過太多緊張考生的椅子。它的腳到現在還在抖。',
    abacus: '帳房先生的算盤，珠子會自己跳。它算得很準，只是從來不算自己。',
    beetle: '在墨裡游泳的甲蟲。殼上的花紋其實是字，只是已經讀不出來了。',
    lanternghost: '放榜那晚要提著回家的燈籠。主人一直沒有回來拿。',
    tidepool: '黑潮退去後留下的水窪。它還記得自己曾經是海。',
    proctor: '騎士團的一員。他分不清你是考生還是怪物，所以兩種都管。',
    bellwraith: '白塔鐘聲的回音。它一直在宣布考試結束，卻沒有任何人離開。',
    nib: '鋼筆斷掉的筆尖。握筆的手放開了它，它卻學會了自己刺。',
    mask: '戴著面具的口試官。面具底下是什麼，沒有一個考生敢問。',
    shadowcat: '唯一一隻被墨染黑的貓。聽說牠是自己走進去的，為了找主人。',
    sandglass: '考場桌上的沙漏。牠的沙永遠流不完，你的時間卻會。',
    mirror: '洗手間鏡子裡的倒影。考生離開了，倒影卻留了下來，學著他的樣子答題。',
    archivist: '管了四十年書庫的老館員。他記得每一本書放在哪裡，卻想不起自己的名字。',
    inkwhale: '在黑色的海裡游蕩的鯨。牠吞下整片文字，吐出來的只剩句點。',
    chainknight: '用鎖鏈把自己綁在白塔大門上的騎士，發誓不讓墨進去。墨是從窗戶進去的。',
    lampeater: '以燈火為食的東西。牠每吃掉一盞燈，世界就暗了一點。',
    grader: '替閱卷官打分數的木偶。線斷了以後，它開始給自己打分數。',
    twins: '坐在相鄰座位的兩個人，約好要一起考上。他們到現在還分不開。',
    blankone: '從空白裡走出來的人。他沒有臉，因為已經沒有人記得他長什麼樣子。',
    tide: '那一晚的浪。直到現在，它還沒有拍完。',
    bellkeeper: '每天敲鐘的老人。那一晚他敲了整整一夜，想把所有人叫醒。',
    eraserking: '所有橡皮擦的盡頭。被它擦過的東西，連「曾經存在過」都會被忘記。',
    lastexaminee: '第七屆最後一個還在答題的人。他寫到最後一題，然後停住了。'
  };

  /* ---------- 首領的圖鑑介紹（以名稱對應） ---------- */
  const BOSS_LORE = {
    '錯字書蠹王': '啃食書頁的蠹蟲之王。牠只吃寫錯的字，吃得太多，連自己都長歪了。',
    '文言幽魂・太史': '替白塔寫歷史的史官。那一晚的紀錄，他只寫了一半。',
    '禁書大巫妖': '看守禁書區的館長。為了不讓任何人讀到最後一題，他把自己變成了最後一道鎖。',
    '成語變臉妖蛾': '收集了所有成語的蛾，每換一張臉就換一個意思。牠早就忘了原本的那一張。',
    '墨龍・書法宗師': '用黑潮寫字的人。他說那晚的墨，是他這輩子用過最好的墨。',
    '科舉判官': '比白塔還古老的考官。他相信每一場考試，都應該有人落榜。',
    '單字吞噬鼠王': '吃掉了整本字典的鼠王。牠會說每一種語言，卻沒有人聽得懂牠。',
    '文法迷宮守衛': '守護語言規則的守衛。他的迷宮只有一條正確的路，句子也是。',
    '克漏字魔女': '把別人說的話挖空的魔女。她只是想知道，大家會在空格裡填上什麼。',
    '拼字女王蜂': '蜂巢的每一格都是一個字母。她在拼一個沒有人知道的詞。',
    '時態鐘塔守衛': '鐘樓的守衛。那一晚之後，他再也分不清過去、現在與未來。',
    '長篇閱讀巨龍': '讀完了整座書庫的龍。牠要找的答案，不在任何一本書裡。',
    '無理數史萊姆王': '吞下了一個除不盡的數，從此再也停不下來。',
    '矩陣魔像': '由白塔的地磚排列而成。每一塊磚都有它的位置，你也是。',
    '極限魔王': '一直在接近某樣東西，卻永遠碰不到。牠很憤怒。',
    '機率骰子惡魔': '骰子賭徒輸給了牠一次。現在輪到牠來擲。',
    '向量水晶巨像': '原本用來指引方向的水晶。現在它所有的方向，都指向下方。',
    '無窮級數之眼': '一直數下去的眼睛。牠數的是落榜的人。',
    '統計鼠群之主': '把所有竄鼠都算進同一張表的鼠王。牠知道你答錯的機率。',
    '複利貪狼盜賊': '在塔裡放高利貸的人。那一晚之後，利息還在繼續算。',
    '三角函數巨像': '測量白塔高度的石像。它算出了塔有多高，也算出了水會漲到多高。',
    '利滾利蟾蜍': '許願池裡最老的蟾蜍。牠收下的硬幣，比實現的願望多得多。',
    '數列燭台妖': '一根接一根點亮的燭台。最後一根，從來沒有被點過。',
    '迴歸線巨像': '想把所有點連成一條直線的巨像。你是它最討厭的那個離群值。',
    '史料盜墓者': '偷走史料的人。他相信，只要沒有人記得，事情就沒有發生過。',
    '季風幽靈': '每年帶來考季的風。現在的它，不知道該往哪裡吹。',
    '帝國遺魂皇帝': '曾經統治這片土地的皇帝。白塔就是他下令建造的。',
    '南瓜地主': '白塔農園的主人。他的田裡種的，不只是南瓜。',
    '鐵幕騎士': '把自己關在鐵幕後面的騎士。他不讓任何人通過，也不讓任何消息進來。',
    '大航海幽靈船長': '駕著船在黑色的海上找出口的船長。他已經繞了很多很多圈。',
    '酸鹼毒蛛': '從實驗室逃出來的蜘蛛。牠的網會溶解你寫下的字。',
    '電磁術士': '塔裡的燈原本是靠他供電的。他想讓燈重新亮起來，卻用了錯誤的方法。',
    '核融合惡魔': '在最深的實驗室裡誕生。牠的熱度能讓墨沸騰。',
    '細胞分裂史萊姆': '從生物教室的標本瓶裡逃出來。牠分裂得比你答題還快。',
    '板塊巨蟹': '背著一整塊大陸的巨蟹。牠每移動一步，深處就裂得更深。',
    '黑洞魔導師': '研究「空白」的學者。他終於明白了空白是什麼，然後就被吸了進去。',
    '墮落考官騎士': '騎士團的團長。他發誓要守護考試的公正，直到最後一名考生交卷。',
    '遠古巨像': '白塔落成之前就站在這裡的巨像。塔是圍著它蓋起來的。',
    '深淵魔王': '黑潮最深處的意志。牠不想傷害任何人，只想讓一切都被忘記。',
    '命題委員・幻影': '寫下最後一題的人留下的影子。他也在等，等有人能答出那一題。'
  };

  C.RELICS.forEach(r => { if (RELIC_LORE[r.id]) r.story = RELIC_LORE[r.id]; });
  C.MONSTERS.forEach(m => { if (MON_LORE[m.id]) m.lore = MON_LORE[m.id]; });
  C.BOSS_LORE = BOSS_LORE;
  C.SECRET_BOSS.lore = BOSS_LORE[C.SECRET_BOSS.name];
  Object.values(C.BOSS_DEFS).forEach(arr => arr.forEach(b => { if (BOSS_LORE[b.name]) b.lore = BOSS_LORE[b.name]; }));
  C.BOSSES.forEach(b => { if (BOSS_LORE[b.name]) b.lore = BOSS_LORE[b.name]; });
})();
