"""Generate an offline, editable-resource preview without browser persistence."""
from pathlib import Path
import json

ROOT=Path(__file__).resolve().parents[1]/'資源'/'114 大一下'
def build():
 packs=[json.loads(p.read_text('utf8')) for p in sorted(ROOT.rglob('學習_*.json'))]
 banks=[json.loads(p.read_text('utf8')) for p in sorted(ROOT.rglob('題庫_*.json')) if not any(x.startswith('.') for x in p.relative_to(ROOT).parts)]
 data=json.dumps({'packs':packs,'sets':banks},ensure_ascii=False).replace('</',r'<\/')
 page=r'''<!doctype html><html lang="zh-Hant"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>114 大一下 · 資源預覽</title><style>
*{box-sizing:border-box}body{margin:0;background:#f7f3e8;color:#2c302a;font:16px/1.7 system-ui,"Microsoft JhengHei",sans-serif}main{max-width:1050px;margin:auto;padding:20px}h1{font-size:28px}select,button{font:inherit;border:1px solid #928b75;border-radius:8px;padding:8px;background:#fff;max-width:100%}select{width:100%}.filters{display:grid;grid-template-columns:1fr 1fr;gap:12px}.filters label{min-width:0}.bar{display:flex;gap:8px;flex-wrap:wrap;margin:15px 0}#panel{background:#fff;padding:22px;border:1px solid #d3cebc;border-radius:12px;min-height:200px}pre{font:inherit;white-space:pre-wrap;overflow-wrap:anywhere;margin:8px 0}.choice{display:block;width:100%;text-align:left;margin:8px 0}.good{background:#e2f5e9}.bad{background:#ffe3d8}iframe{border:0;width:100%;background:#fbf7ec}img{max-width:100%}.diagram{position:relative;max-width:800px}.diagram img{display:block;width:100%}.mark{position:absolute;transform:translate(-50%,-50%);border:2px solid #5e4530;border-radius:50%;background:#fff3ae;width:28px;height:28px;padding:0;font-size:14px}#stat{color:#5a6256}details{background:#f5f2e9;padding:8px;margin:8px 0}li{margin:6px 0}@media(max-width:600px){main{padding:12px}.filters{grid-template-columns:1fr}#panel{padding:12px}h1{font-size:24px}}
</style><main><h1>114 大一下 · 資源預覽</h1><p id="stat"></p><div class="filters"><label>年份／教材年度<select id="year"></select></label><label>科目<select id="subject"></select></label><label>模式<select id="mode"><option value="learn">📘 學習課程</option><option value="bank">📝 原題庫</option></select></label><label>單元／題本<select id="unit"></select></label><label id="lessonLabel">課程<select id="lesson"></select></label></div><div class="bar"><button id="prev">上一段</button><span id="position"></span><button id="next">下一段</button></div><article id="panel"></article><p>正式遊戲：營地 → 📥 導入素材 → 選「114 大一下」整個資料夾。本預覽不保存學習紀錄。</p></main><script>const DATA=__DATA__;
const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let list=[],index=0,active=[];const subjects={eye_ans:'眼解剖生理學',physio:'生理學',optometry:'視光學',basic_optics:'基礎光學'};const qmap=new Map(DATA.sets.flatMap(s=>s.questions.map(q=>[s.set.id+'-'+q.n,q])));function text(x){return '<pre>'+esc(Array.isArray(x)?x.join('\n'):x).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>')+'</pre>';}function opts(select,entries){select.innerHTML=entries.map(([v,t])=>`<option value="${esc(v)}">${esc(t)}</option>`).join('');}opts($('subject'),Object.entries(subjects));opts($('year'),[['all','全部'],...Array.from(new Set([...DATA.packs.map(p=>p.path[1]),...DATA.sets.map(s=>s.set.path[1])])).sort().map(x=>[x,x])]);$('stat').textContent=`${DATA.sets.reduce((n,s)=>n+s.questions.length,0)} 題 · ${DATA.packs.length} 單元檔 · ${DATA.packs.reduce((n,p)=>n+p.lessons.length,0)} 課`;
function filter(){const bank=$('mode').value==='bank';list=(bank?DATA.sets:DATA.packs).filter(x=>{const p=bank?x.set:x;return p.subject===$('subject').value&&($('year').value==='all'||p.path[1]===$('year').value)});opts($('unit'),list.map((x,i)=>[i,bank?x.set.name:x.title]));$('lessonLabel').hidden=bank;selectUnit();}function selectUnit(){const obj=list[Number($('unit').value)];if(!obj){active=[];$('panel').textContent='這個分類沒有資料。';$('position').textContent='';return;}if($('mode').value==='bank'){active=obj.questions;index=0;render();}else{opts($('lesson'),obj.lessons.map((l,i)=>[i,l.title]));selectLesson();}}function selectLesson(){const p=list[Number($('unit').value)];active=p?.lessons[Number($('lesson').value)]?.steps||[];index=0;render();}
function renderCheck(c,target){const isBank=!!c.stem;target.innerHTML=text(c.q||c.stem);(c.img||[]).forEach(im=>target.insertAdjacentHTML('beforeend',`<img src="${esc(im)}">`));const choices=c.choices||[];let wrong=0;if(choices.length){choices.forEach((ch,i)=>{const b=document.createElement('button');b.className='choice';b.textContent=String.fromCharCode(65+i)+'. '+ch;b.onclick=()=>{let correct=isBank?String(c.answer).includes(String.fromCharCode(65+i)):c.answer===i;if(correct){b.classList.add('good');out.innerHTML=text('答對。\n'+c.explain);}else{b.classList.add('bad');wrong++;out.innerHTML=text(wrong===1?(c.hint||'先回到相關概念，確認方向與條件。'):c.explain);}};target.append(b);});}else{const b=document.createElement('button');b.textContent='顯示參考答案／自評';b.onclick=()=>{out.innerHTML=text(c.answer||c.items?.join(' → '))+text(c.explain)};target.append(b);}const out=document.createElement('div');out.setAttribute('aria-live','polite');target.append(out);}
function render(){const s=active[index],p=$('panel');$('position').textContent=`${index+1} / ${active.length}`;$('prev').disabled=index===0;$('next').disabled=index>=active.length-1;if(!s){p.textContent='無資料';return;}p.innerHTML='<h2>'+esc(s.title||s.type||'原題')+'</h2>';if(s.stem||s.type==='check'){renderCheck(s,p);return;}if(s.type==='interactive'){p.insertAdjacentHTML('beforeend',text(s.task));const f=document.createElement('iframe');f.title=s.title;f.setAttribute('sandbox','allow-scripts');f.style.height=(s.height||500)+'px';f.srcdoc=Array.isArray(s.html)?s.html.join('\n'):s.html;p.append(f);return;}if(s.type==='diagram'){p.insertAdjacentHTML('beforeend',text(s.body)+`<div class="diagram"><img src="${esc(s.img)}" alt="${esc(s.title)}"></div><div id="desc">點選圖中編號。</div>`);s.points.forEach((pt,i)=>{const b=document.createElement('button');b.className='mark';b.textContent=i+1;b.style.left=pt.x+'%';b.style.top=pt.y+'%';b.setAttribute('aria-label',pt.name);b.onclick=()=>{$('desc').innerHTML='<b>'+esc(pt.name)+'</b>'+text(pt.desc)};p.querySelector('.diagram').append(b);});return;}if(s.type==='practice'){const cs=[...(s.checks||[]),...(s.qids||[]).map(id=>qmap.get(id)).filter(Boolean)];cs.forEach((c,i)=>{const d=document.createElement('details'),sm=document.createElement('summary');sm.textContent='實戰 '+(i+1);d.append(sm);const box=document.createElement('div');renderCheck(c,box);d.append(box);p.append(d)});return;}p.insertAdjacentHTML('beforeend',text(s.body||s.problem||''));if(s.type==='example'){p.insertAdjacentHTML('beforeend','<ol>'+s.steps.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ol>'+text(s.answer));}if(s.type==='recap'){p.insertAdjacentHTML('beforeend','<ul>'+s.points.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>');s.flash.forEach(f=>p.insertAdjacentHTML('beforeend','<details><summary>'+esc(f.front)+'</summary>'+text(f.back)+'</details>'));}if(s.keys)p.insertAdjacentHTML('beforeend','<ul>'+s.keys.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>');}
['subject','year','mode'].forEach(id=>$(id).onchange=filter);$('unit').onchange=selectUnit;$('lesson').onchange=selectLesson;$('prev').onclick=()=>{index--;render()};$('next').onclick=()=>{index++;render()};filter();</script></html>'''
 (ROOT/'預覽.html').write_text(page.replace('__DATA__',data),encoding='utf8')
if __name__=='__main__':build()
